# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/uiFiles/loginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(790, 556)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint) # Added
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground) # Added
        font = QtGui.QFont()
        font.setKerning(True)
        Form.setFont(font)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(37, 29, 731, 500))
        self.widget.setStyleSheet("QPushButton#submitBtn{\n"
"    background-color: #2d9272;\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#submitBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop: 1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#submitBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"#closeBtn:hover{\n"
"background-color: #9bc7a8;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(171, 73, 263, 262))
        self.label.setStyleSheet("border-image:url(:/newPrefix/Colored Solid Color.svg);\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(449, 30, 271, 430))
        self.label_3.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"border-bottom-right-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(530, 110, 104, 40))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.label_4.setObjectName("label_4")
        self.username = QtWidgets.QLineEdit(self.widget)
        self.username.setGeometry(QtCore.QRect(520, 178, 160, 40))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(10)
        font.setKerning(True)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color:rbga(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rbga(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;")
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(520, 238, 159, 40))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(10)
        font.setKerning(True)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rbga(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rbga(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.submitBtn = QtWidgets.QPushButton(self.widget)
        self.submitBtn.setGeometry(QtCore.QRect(537, 307, 105, 34))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.submitBtn.setFont(font)
        self.submitBtn.setStyleSheet("")
        self.submitBtn.setObjectName("submitBtn")
        self.closeBtn = QtWidgets.QPushButton(self.widget)
        self.closeBtn.setGeometry(QtCore.QRect(690, 40, 21, 21))
        self.closeBtn.setStyleSheet("border-image: url(:/blackIcons/feather/x.svg);\n"
"")
        self.closeBtn.setText("")
        self.closeBtn.setObjectName("closeBtn")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(484, 189, 27, 25))
        self.widget_2.setStyleSheet("image: url(:/newPrefix/user.svg);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(485, 247, 26, 28))
        self.widget_3.setStyleSheet("image: url(:/newPrefix/lock.svg);")
        self.widget_3.setObjectName("widget_3")
        self.loginMsg = QtWidgets.QLabel(self.widget)
        self.loginMsg.setGeometry(QtCore.QRect(515, 277, 221, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.loginMsg.setFont(font)
        self.loginMsg.setStyleSheet("font: 8pt \"MS Shell Dlg 2\"; color: rgb(255, 156, 43);")
        self.loginMsg.setText("")
        self.loginMsg.setObjectName("loginMsg")

        
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0)) # Added
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0)) # Added
        self.submitBtn.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3)) # Added

        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(158, 320, 285, 79))
        self.label_2.setStyleSheet("border-image:url(:/newPrefix/Label1.svg);\n"
"border-top-left-radius: 50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(151, 30, 530, 431))
        self.label_5.setStyleSheet("border-image:url(:/newPrefix/bg.svg);\n"
"border-top-left-radius: 50px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(200, 410, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font: 75 7pt \"Moon\";")
        self.label_13.setObjectName("label_13")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(180, 380, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 75 9pt \"Moon\";")
        self.label_6.setObjectName("label_6")
        self.label_5.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.username.raise_()
        self.password.raise_()
        self.submitBtn.raise_()
        self.closeBtn.raise_()
        self.widget_2.raise_()
        self.widget_3.raise_()
        self.loginMsg.raise_()
        self.label_2.raise_()
        self.label_13.raise_()
        self.label_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Sign In"))
        self.username.setPlaceholderText(_translate("Form", "Username"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.submitBtn.setText(_translate("Form", "Login"))
        self.label_13.setText(_translate("Form", "Desktop Application System"))
        self.label_6.setText(_translate("Form", "Data Storage and Retrieval"))
        
from . import resource_rc
